### ISSUE TITLE
Rename FIST to SPOT in Makefile :p

### ISSUE THREAD

**Issue by jlevallois** [nbonneel/spot#2]
The documentation says that the Makefile will generate an executable named `SPOT`, but will generate `FIST` instead.
Please update the documentation or the two Makefile files :)

:octocat:

**Comment by dcoeurjo** [comment]
well.. the code illustrates the point cloud registration (FIST) that uses the  Sliced Partial Optimal Transport (SPOT) ;)

**Comment by dcoeurjo** [comment]
We should update the README rather than the makefile.. 👍

**Comment by dcoeurjo** [comment]
done, thx
