### ISSUE TITLE
About the renderer..

### ISSUE THREAD

**Issue by wzm2256** [nbonneel/spot#7]
Hi, I have a question that is not directly relevant to your code...
How to render a point cloud as in your paper? I'm from machine learning community and I'm not familiar with 3D rendering.

Thanks a lot for your time.

**Comment by nbonneel** [comment]
all 3d renderings in the paper were done with my path tracer: https://github.com/nbonneel/pathtracer
You can drag'n drop an .xyz file containing 3d coordinates (3 columns, ascii file) and it renders.
